### ISSUE TITLE
[support] How to use fixtures ?

### ISSUE THREAD

**Issue by drupol** [warhuhn/chronos-doctrine#4]
Hello,

I'm trying to use your package and generate some records with fixtures with [nelmio/alice](https://github.com/hautelook/AliceBundle).

However, I'm unable to generate them. Could you please give me some support/guidance on how to use your package ?

You can find the [project here](https://github.com/drupol/doctrine-date-as-id/pull/2), it's a basic project with only 1 entity having a composite primary key with a DateTime field type in it.

Thanks!

**Comment by warhuhn** [comment]
Hi,

The suggestion by @beberlei was correct, it should work since Chronos has a __toString() function.

However, your fixtures fail because the DateTime generator used by Alice doesn't use Chronos objects and they are never converted to Chronos objects.

You have to write a getter and setter method for your Entity class that will convert values given to the object to Chronos objects.

Example:

```php
    public function setDateValue($dateValue): void {
        if ($dateValueinstanceof Chronos) { // if we get a chronos object, take that.
            $this->dateValue= $dateValue;
        } else if ($dateValueinstanceof DateTimeInterface || is_string($dateValue)) { // if it's a DateTime object that's not chronos or a string, try to convert it to chronos.
            $this->dateValue= Chronos::parse($dateValue);
        }
    }

    public function getDateValue(): Chronos {
        return $this->dateValue;
    }
}
```


Does this help you out?

**Comment by drupol** [comment]
Hi,

Thanks for the fast reply!

In the meantime, I did something else and it seems to work. Many thanks for the inspiration !!!

I'm copy pasting here the traits I'm using in order to get this working, in case if someone is looking for that.

```php
<?php

declare(strict_types=1);

namespace App\Entity\Traits;

use Cake\Chronos\Chronos;
use Doctrine\ORM\Mapping as ORM;

trait EventdateField
{
    /**
     * @var Chronos
     * @ORM\Id
     * @ORM\Column(type="chronos_datetime", name="EVENTDATE")
     */
    protected $eventdate;

    public function getEventdate(): Chronos
    {
        return $this->eventdate;
    }

    public function setEventdate($dateValue): void
    {
        $this->eventdate = Chronos::parse($dateValue);
    }
}
```

**Comment by warhuhn** [comment]
Well, that's exactly what i suggested you do. Wether the getter/setter methods are inside a trait or the class itself doesn't really matter.
